import { db } from "./db";
import { questionCategories, questions } from "@shared/schema";

const seedCategories = [
  {
    id: 1,
    name: "Demographics",
    description: "Basic demographic information",
    isEnabled: true,
    sortOrder: 1,
  },
  {
    id: 2,
    name: "Beliefs & Values",
    description: "Personal beliefs and value systems",
    isEnabled: true,
    sortOrder: 2,
  },
  {
    id: 3,
    name: "Lifestyle",
    description: "Lifestyle preferences and habits",
    isEnabled: true,
    sortOrder: 3,
  },
  {
    id: 4,
    name: "Career & Education",
    description: "Professional and educational background",
    isEnabled: true,
    sortOrder: 4,
  },
  {
    id: 5,
    name: "Media Preferences",
    description: "Media consumption habits and preferences",
    isEnabled: true,
    sortOrder: 5,
  },
  {
    id: 6,
    name: "Technology Usage",
    description: "Technology adoption and usage patterns",
    isEnabled: true,
    sortOrder: 6,
  },
  {
    id: 7,
    name: "Buying Behavior",
    description: "Shopping habits and purchasing decisions",
    isEnabled: true,
    sortOrder: 7,
  },
  {
    id: 8,
    name: "Psychographics",
    description: "Personality traits and psychological characteristics",
    isEnabled: true,
    sortOrder: 8,
  },
];

const seedQuestions = [
  // Demographics (Category 1)
  {
    categoryId: 1,
    question: "What is your age?",
    questionType: "number",
    options: null,
    isRequired: true,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 1,
    question: "What is your gender?",
    questionType: "select",
    options: JSON.stringify(["Male", "Female", "Non-binary", "Prefer not to say", "Other"]),
    isRequired: true,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 1,
    question: "What is your ethnicity?",
    questionType: "select",
    options: JSON.stringify(["White", "Black/African American", "Hispanic/Latino", "Asian", "Native American", "Pacific Islander", "Mixed", "Other", "Prefer not to say"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 1,
    question: "What country do you live in?",
    questionType: "text",
    options: null,
    isRequired: true,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 1,
    question: "What city do you live in?",
    questionType: "text",
    options: null,
    isRequired: true,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 1,
    question: "What is your marital status?",
    questionType: "select",
    options: JSON.stringify(["Single", "Married", "Divorced", "Widowed", "In a relationship", "Prefer not to say"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    categoryId: 1,
    question: "How many people live in your household?",
    questionType: "number",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 7,
  },
  {
    categoryId: 1,
    question: "Do you have children?",
    questionType: "boolean",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 8,
  },

  // Beliefs & Values (Category 2)
  {
    categoryId: 2,
    question: "What is your religious affiliation?",
    questionType: "select",
    options: JSON.stringify(["Christianity", "Islam", "Judaism", "Hinduism", "Buddhism", "Atheist", "Agnostic", "Other", "Prefer not to say"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 2,
    question: "What is your political affiliation?",
    questionType: "select",
    options: JSON.stringify(["Very Liberal", "Liberal", "Moderate", "Conservative", "Very Conservative", "Independent", "Other", "Prefer not to say"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 2,
    question: "How concerned are you about environmental issues?",
    questionType: "scale",
    options: JSON.stringify({min: 1, max: 10, labels: ["Not concerned", "Extremely concerned"]}),
    isRequired: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 2,
    question: "Which social causes are important to you?",
    questionType: "multiselect",
    options: JSON.stringify(["Climate change", "Social justice", "Education", "Healthcare", "Poverty", "Animal rights", "Human rights", "Technology ethics", "None", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 2,
    question: "Do you regularly volunteer or donate to charity?",
    questionType: "boolean",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 2,
    question: "How important is work-life balance to you?",
    questionType: "scale",
    options: JSON.stringify({min: 1, max: 10, labels: ["Not important", "Extremely important"]}),
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },

  // Lifestyle (Category 3)
  {
    categoryId: 3,
    question: "What are your main hobbies?",
    questionType: "multiselect",
    options: JSON.stringify(["Reading", "Sports", "Music", "Art", "Gaming", "Cooking", "Gardening", "Travel", "Photography", "Writing", "Crafts", "Technology", "Fitness", "Movies/TV", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 3,
    question: "How would you describe your fitness level?",
    questionType: "select",
    options: JSON.stringify(["Very fit", "Moderately fit", "Average", "Below average", "Not fit"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 3,
    question: "How often do you exercise?",
    questionType: "select",
    options: JSON.stringify(["Daily", "4-6 times per week", "2-3 times per week", "Once per week", "Rarely", "Never"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 3,
    question: "Do you have any dietary restrictions?",
    questionType: "multiselect",
    options: JSON.stringify(["Vegetarian", "Vegan", "Gluten-free", "Dairy-free", "Keto", "Paleo", "Halal", "Kosher", "No restrictions", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 3,
    question: "How many hours of sleep do you typically get per night?",
    questionType: "number",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 3,
    question: "How often do you socialize with friends/family?",
    questionType: "select",
    options: JSON.stringify(["Daily", "Several times per week", "Weekly", "Monthly", "Rarely", "Never"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    categoryId: 3,
    question: "How would you rate your current stress level?",
    questionType: "scale",
    options: JSON.stringify({min: 1, max: 10, labels: ["Very low", "Very high"]}),
    isRequired: false,
    isEnabled: true,
    sortOrder: 7,
  },

  // Career & Education (Category 4)
  {
    categoryId: 4,
    question: "What is your highest level of education?",
    questionType: "select",
    options: JSON.stringify(["High school", "Some college", "Associate degree", "Bachelor's degree", "Master's degree", "Doctoral degree", "Professional degree", "Other"]),
    isRequired: true,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 4,
    question: "What was your field of study?",
    questionType: "text",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 4,
    question: "What is your current employment status?",
    questionType: "select",
    options: JSON.stringify(["Full-time employed", "Part-time employed", "Self-employed", "Unemployed", "Student", "Retired", "Homemaker", "Other"]),
    isRequired: true,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 4,
    question: "What industry do you work in?",
    questionType: "select",
    options: JSON.stringify(["Technology", "Healthcare", "Finance", "Education", "Retail", "Manufacturing", "Government", "Non-profit", "Media", "Real estate", "Transportation", "Hospitality", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 4,
    question: "What is your job title?",
    questionType: "text",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 4,
    question: "How many years of work experience do you have?",
    questionType: "number",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    categoryId: 4,
    question: "What is your annual household income?",
    questionType: "select",
    options: JSON.stringify(["Under $25,000", "$25,000-$49,999", "$50,000-$74,999", "$75,000-$99,999", "$100,000-$149,999", "$150,000-$199,999", "$200,000+", "Prefer not to say"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 7,
  },
  {
    categoryId: 4,
    question: "Do you work from home?",
    questionType: "select",
    options: JSON.stringify(["Always", "Most of the time", "Sometimes", "Rarely", "Never", "Not applicable"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 8,
  },

  // Media Preferences (Category 5)
  {
    categoryId: 5,
    question: "What TV genres do you enjoy?",
    questionType: "multiselect",
    options: JSON.stringify(["Drama", "Comedy", "Action", "Horror", "Documentary", "Reality TV", "News", "Sports", "Sci-Fi", "Fantasy", "Romance", "Mystery", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 5,
    question: "Which streaming platforms do you use?",
    questionType: "multiselect",
    options: JSON.stringify(["Netflix", "Amazon Prime", "Disney+", "HBO Max", "Hulu", "Apple TV+", "YouTube Premium", "Spotify", "Other", "None"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 5,
    question: "What music genres do you enjoy?",
    questionType: "multiselect",
    options: JSON.stringify(["Pop", "Rock", "Hip-hop", "Country", "Classical", "Jazz", "Electronic", "Folk", "R&B", "Alternative", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 5,
    question: "How do you primarily consume news?",
    questionType: "select",
    options: JSON.stringify(["TV", "Online news sites", "Social media", "Newspapers", "Radio", "Podcasts", "I don't follow news", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 5,
    question: "How many hours per day do you spend on social media?",
    questionType: "number",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 5,
    question: "Do you listen to podcasts?",
    questionType: "boolean",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    categoryId: 5,
    question: "How many hours per week do you spend gaming?",
    questionType: "number",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 7,
  },

  // Technology Usage (Category 6)
  {
    categoryId: 6,
    question: "Which devices do you regularly use?",
    questionType: "multiselect",
    options: JSON.stringify(["iPhone", "Android phone", "iPad", "Android tablet", "Windows PC", "Mac", "Smart TV", "Gaming console", "Smart watch", "Other"]),
    isRequired: true,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 6,
    question: "What is your primary computer operating system?",
    questionType: "select",
    options: JSON.stringify(["Windows", "macOS", "Linux", "Chrome OS", "I don't use a computer", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 6,
    question: "What is your preferred web browser?",
    questionType: "select",
    options: JSON.stringify(["Chrome", "Safari", "Firefox", "Edge", "Opera", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 6,
    question: "Which social media platforms do you use?",
    questionType: "multiselect",
    options: JSON.stringify(["Facebook", "Instagram", "Twitter/X", "LinkedIn", "TikTok", "YouTube", "Snapchat", "Reddit", "Pinterest", "Discord", "Other", "None"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 6,
    question: "How comfortable are you with new technology?",
    questionType: "scale",
    options: JSON.stringify({min: 1, max: 10, labels: ["Very uncomfortable", "Very comfortable"]}),
    isRequired: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 6,
    question: "What types of apps do you use most?",
    questionType: "multiselect",
    options: JSON.stringify(["Social media", "News", "Gaming", "Shopping", "Finance", "Health", "Travel", "Food delivery", "Productivity", "Entertainment", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    categoryId: 6,
    question: "How many hours per day do you spend on the internet?",
    questionType: "number",
    options: null,
    isRequired: false,
    isEnabled: true,
    sortOrder: 7,
  },

  // Buying Behavior (Category 7)
  {
    categoryId: 7,
    question: "How often do you shop online?",
    questionType: "select",
    options: JSON.stringify(["Daily", "Weekly", "Monthly", "Rarely", "Never"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 7,
    question: "Where do you shop online most often?",
    questionType: "multiselect",
    options: JSON.stringify(["Amazon", "eBay", "Walmart", "Target", "Best Buy", "Brand websites", "Social media shopping", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 7,
    question: "How important is brand loyalty to you?",
    questionType: "scale",
    options: JSON.stringify({min: 1, max: 10, labels: ["Not important", "Very important"]}),
    isRequired: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 7,
    question: "What most influences your purchasing decisions?",
    questionType: "multiselect",
    options: JSON.stringify(["Price", "Quality", "Brand reputation", "Reviews", "Recommendations", "Advertising", "Social media", "Environmental impact", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 7,
    question: "How much do you typically spend on discretionary purchases per month?",
    questionType: "select",
    options: JSON.stringify(["Under $100", "$100-$299", "$300-$499", "$500-$999", "$1000-$1999", "$2000+", "Prefer not to say"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 7,
    question: "How often do you make impulse purchases?",
    questionType: "select",
    options: JSON.stringify(["Very often", "Often", "Sometimes", "Rarely", "Never"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    categoryId: 7,
    question: "What motivates you to shop?",
    questionType: "multiselect",
    options: JSON.stringify(["Necessity", "Entertainment", "Stress relief", "Social activity", "Deals/discounts", "Trying new things", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 7,
  },

  // Psychographics (Category 8)
  {
    categoryId: 8,
    question: "How would you describe your personality?",
    questionType: "select",
    options: JSON.stringify(["Very introverted", "Somewhat introverted", "Balanced", "Somewhat extroverted", "Very extroverted"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    categoryId: 8,
    question: "What is your preferred learning style?",
    questionType: "select",
    options: JSON.stringify(["Visual", "Auditory", "Kinesthetic", "Reading/Writing", "Mixed", "Not sure"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    categoryId: 8,
    question: "How do you feel about taking risks?",
    questionType: "scale",
    options: JSON.stringify({min: 1, max: 10, labels: ["Very risk-averse", "Very risk-tolerant"]}),
    isRequired: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    categoryId: 8,
    question: "How do you typically make decisions?",
    questionType: "select",
    options: JSON.stringify(["Quickly and intuitively", "After careful analysis", "I ask others for advice", "I research extensively", "It depends on the situation"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    categoryId: 8,
    question: "What motivates you most?",
    questionType: "multiselect",
    options: JSON.stringify(["Achievement", "Recognition", "Money", "Helping others", "Personal growth", "Creativity", "Security", "Freedom", "Other"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    categoryId: 8,
    question: "How do you prefer to communicate?",
    questionType: "select",
    options: JSON.stringify(["Face-to-face", "Phone calls", "Video calls", "Text messages", "Email", "Social media", "It depends"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    categoryId: 8,
    question: "How do you handle conflict?",
    questionType: "select",
    options: JSON.stringify(["Avoid it", "Address it directly", "Seek mediation", "Compromise", "Stand firm", "It depends"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 7,
  },
  {
    categoryId: 8,
    question: "When it comes to new products/services, you are:",
    questionType: "select",
    options: JSON.stringify(["First to try", "Early adopter", "Wait and see", "Need proof it works", "Last to adopt"]),
    isRequired: false,
    isEnabled: true,
    sortOrder: 8,
  },
];

export async function seedDatabase() {
  console.log("Seeding database...");
  
  try {
    // Insert categories
    await db.insert(questionCategories).values(seedCategories).onConflictDoNothing();
    console.log("Categories seeded successfully");
    
    // Insert questions
    await db.insert(questions).values(seedQuestions).onConflictDoNothing();
    console.log("Questions seeded successfully");
    
    console.log("Database seeded successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

// Run seeding if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedDatabase().then(() => {
    console.log("Seeding complete");
    process.exit(0);
  }).catch((error) => {
    console.error("Seeding failed:", error);
    process.exit(1);
  });
}